<?php

namespace app\admin\controller;
use think\Controller;

class Book extends Controller{
    //控制器初始化方法_initialize，在该控制器的方法调用之前首先执行。
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('?email')){
            $this->redirect('admin/user/login');
        }
    }


    public function booklist(){
//        // 查询状态为1的用户数据 并且每页显示10条数据
//        $list = User::where('status',1)->paginate(10);
//// 把分页数据赋值给模板变量list
//        $this->assign('list', $list);
//// 渲染模板输出
//        return $this->fetch();
        $list=model('Book')->paginate(3);
        $this->assign('list', $list);
        return $this->fetch();
    }
    public function bookadd(){
        if(request()->isAjax()){
            $data=[
                'isbn' =>input('isbn'),
                'name' =>input('name'),
                'price'=>input('price'),
                'num'=>input('num'),
                'picture'=>input('picture'),
            ];
            $res=model('Book')->bookadd($data);
            if($res==1){
                $this->success('添加图书成功！','admin/book/booklist');
            }else{
                $this->error($res);
            }
        }
        return view();
    }

    public function one(){
        //isbn
        $data=[
            'isbn'=>input('isbn'),
        ];
        $onebook=model("Book")->where('isbn',$data['isbn'])->find();
        $this->assign('one', $onebook);
        return $this->fetch();


    }
    public function bookdelete(){
        $data=[
            'isbn'=>input('isbn'),
        ];
        model("Book")->where('isbn',$data['isbn'])->delete();
        $this->success('删除图书成功！','admin/book/booklist');
    }
    public function bookedit(){
        if(request()->isAjax()){
            $data=[
                'isbn' =>input('isbn'),
                'name' =>input('name'),
                'price'=>input('price'),
                'num'=>input('num'),
                'picture'=>input('picture'),
            ];
            $res=model('Book')->bookedit($data);
            if($res==1){
                $this->success('更新图书成功！','admin/book/booklist');
            }else{
                $this->error($res);
            }
        }
        $data=[
            'isbn'=>input('isbn'),
        ];
        $onebook=model("Book")->where('isbn',$data['isbn'])->find();
        $this->assign('one', $onebook);
        return $this->fetch();
    }

}